# Generated by Django 3.0.7 on 2022-11-07 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('igrant_user', '0002_auto_20221031_1149'),
    ]

    operations = [
        migrations.RenameField(
            model_name='igrantuser',
            old_name='org',
            new_name='organisation',
        ),
        migrations.AlterField(
            model_name='igrantuser',
            name='user_type',
            field=models.CharField(choices=[('COMPANY', 'Company'), ('ISSUER', 'Issuer'), ('BUYER', 'Buyer'), ('SELLER', 'Seller')], default='COMPANY', max_length=8),
        ),
    ]
